#!/usr/bin/env escript

run_test(File) ->
   {module, Module} = code:load_abs(filename:join(filename:dirname(File), filename:basename(File, ".beam"))),
   io:format("~p -> ", [Module]),
   case (catch apply(Module, test, [])) of
      {'EXIT', {undef, [{Module, test, []}|_Rest]}} ->
         io:format("tests not found~n");
      Other ->
         io:format("~p~n", [Other])
   end.

main([Dir]) ->
   code:add_patha(Dir),
   error_logger:tty(false),
   io:format("Run unit tests:~n"),
   filelib:fold_files(Dir, ".*\.beam", false, fun(F, _) -> run_test(F) end, 0),
   ok.
