#!/usr/bin/env escript

-export([main/1]).

decode(<<>>, _Context) ->
   ok;
decode(Data, Context) ->
   {Msg, Data1, Context1} = erlang_fast:decode(Data, Context),
   io:format("~p~n", [Msg]),
   Context2 = case Msg of
      {120, _} -> erlang_fast:reset(Context1);
      _ -> Context1
   end,
   decode(Data1, Context2).

main([Template, DataFile]) ->
   F = fun([], _) -> ok;
          (Err, Val) -> io:format("~p: ~p~n", [Err, Val]) end,
   Context = erlang_fast:create_context({file, Template}, F),
   {ok, Data} = file:read_file(DataFile),
   decode(Data, Context),
   ok;
main(_) ->
  io:format("Usage: decode <template> <bin_data>~n").
