-record(templates, {ns = undef, templateNs = undef, dictionary = undef, tlist}).
-record(template, {name, templateNs = undef, id = undef, ns = undef, dictionary = undef, instructions}).
-record(typeRef, {name, ns = undef}).
-record(templateRef, {name, templateNs = undef, ns = undef}).
-record(field, {type, name, disp_name, ns = undef, id = undef, presence = mandatory, operator = undef}).
-record(field_group, {type, name, disp_name, ns = undef, id = undef, presence = mandatory, need_pmap = false, dictionary = undef, instructions}).
-record(constant, {value = undef}).
-record(default,  {value = undef}).
-record(copy, {dictionary = undef, key = undef, ns = undef, value = undef}).
-record(increment, {dictionary = undef, key = undef, ns = undef, value = undef}).
-record(delta, {dictionary = undef, key = undef, ns = undef, value = undef}).
-record(tail, {dictionary = undef, key = undef, ns = undef, value = undef}).
-record(decFieldOp, {exponent, mantissa}).
